"""
Local LLM service for Lighthouse.

This is the first safe version of the Lighthouse AI layer.

For now, it does not call an external or local model.
It uses the existing Lighthouse insight engine to produce an assistant-style
answer from read-only system telemetry and event-log evidence.

Later, this module can be upgraded to call Ollama or another local model.
"""

from typing import Any

from app.collectors.event_logs import get_recent_system_events
from app.main import collect_telemetry
from app.services.insights import build_system_insight


def build_lighthouse_context(user_question: str) -> dict[str, Any]:
    """
    Build the context needed to answer a Lighthouse question.

    This collects read-only telemetry and event-log evidence, then builds
    a structured insight from those facts.
    """
    telemetry = collect_telemetry()
    event_report = get_recent_system_events(limit=100)

    insight = build_system_insight(
        telemetry=telemetry,
        event_report=event_report,
    )

    return {
        "status": "ok",
        "question": user_question,
        "telemetry": telemetry,
        "event_report": event_report,
        "insight": insight,
    }


def format_lighthouse_answer(
    user_question: str,
    insight: dict[str, Any],
) -> str:
    """
    Format a Lighthouse assistant-style answer.

    This is intentionally deterministic for now.
    The wording is generated from known Lighthouse facts, not from a model.
    """
    overall_status = insight.get("overall_status", "UNKNOWN")
    summary = insight.get("summary", "No summary available.")
    conclusion = insight.get("conclusion", "No conclusion available.")
    findings = insight.get("findings", [])
    recommendations = insight.get("recommendations", [])

    lines: list[str] = []

    lines.append("")
    lines.append("LIGHTHOUSE ASSISTANT")
    lines.append("=" * 52)
    lines.append(f"Question: {user_question}")
    lines.append("")
    lines.append(f"Overall status: {overall_status}")
    lines.append("")
    lines.append("Answer:")
    lines.append(f"- {summary}")
    lines.append(f"- {conclusion}")

    if findings:
        lines.append("")
        lines.append("Evidence:")

        for finding in findings:
            lines.append(f"- {finding}")

    if recommendations:
        lines.append("")
        lines.append("Suggested next step:")

        for recommendation in recommendations:
            lines.append(f"- {recommendation}")

    lines.append("")
    lines.append("AI mode:")
    lines.append("- Local LLM is not enabled yet.")
    lines.append("- This answer was generated by the Lighthouse insight engine.")
    lines.append("=" * 52)

    return "\n".join(lines)


def ask_lighthouse(user_question: str) -> dict[str, Any]:
    """
    Answer a user question using Lighthouse's current safe assistant layer.
    """
    cleaned_question = user_question.strip()

    if not cleaned_question:
        return {
            "status": "error",
            "message": "No question provided.",
        }

    try:
        context = build_lighthouse_context(cleaned_question)
        insight = context.get("insight", {})

        answer = format_lighthouse_answer(
            user_question=cleaned_question,
            insight=insight,
        )

        return {
            "status": "ok",
            "provider": "lighthouse_insight_engine",
            "model": "deterministic_stub",
            "uses_external_ai": False,
            "question": cleaned_question,
            "answer": answer,
            "insight": insight,
        }

    except Exception as error:
        return {
            "status": "error",
            "message": f"Failed to answer Lighthouse question: {error}",
        }